# Generated by Django 3.2.2 on 2021-07-30 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='your_name',
            new_name='name',
        ),
    ]
